services:
  pik-nlp:
    gpus: all
    environment:
      - DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

# docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d